version: '3'

services:
  refero-backend:
    image: refero-backend
    ports:
      - 8080:8080
  refero-web-ui:
    image: refero-web-ui
    ports:
      - 4200:4200
      - 80:4200
      - 443:4200
