version: '3'

services:
  refero-backend:
    image: refero:refero-backend
    container_name: refero-backend
    ports:
      - 8080:8080
    networks:
      - net

  database:
    image: postgres
    ports:
      - 5432:5432
    container_name: postgres-database
    environment:
      - POSTGRES_USER=sample
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=refero
    networks:
      - net
    volumes:
      - data:/var/lib/postgresql/data

  refero-web-ui:
    image: refero:refero-web-ui
    container_name: refero-web-ui
    environment:
      - DOMAIN_NAME=localhost
    ports:
      - 80:80
    networks:
      - net

volumes:
  data:

networks:
  net:
