### 
GET http://localhost:8080/refs HTTP/1.1
content-type: application/json

### 
GET http://localhost:8080/cols?ref_id=refid1 HTTP/1.1
content-type: application/json


### 
GET http://localhost:8080/refs/askjasl39493 HTTP/1.1
content-type: application/json

### 
GET http://localhost:8080/cols HTTP/1.1
content-type: application/json


### 
GET http://localhost:8080/records HTTP/1.1
content-type: application/json


### 
POST http://localhost:8080/records HTTP/1.1
content-type: application/json

{
    "id": "dskjghdskjw0448092",
    "fields": {
        "toad": "tulip",
        "totally": "blabla"
    },
    "ref_id": "test38420935"
}


### 
POST http://localhost:8080/cols HTTP/1.1
content-type: application/json

{
    "id": "sajlkasjfaslkfja",
    "name": "REE_NOGA",
    "colType": "FK",
    "ref_id": "askjasl39493"

}

### 
POST http://localhost:8080/views HTTP/1.1
content-type: application/json

{
    "id": "sajlkasjfaslkfja",
    "name": "REE_NOGA",
    "colType": "FK",
    "ref_id": "askjasl39493"

}

