### 
GET http://localhost:8080 HTTP/1.1
content-type: application/json

### 
GET http://localhost:8080/refs HTTP/1.1
content-type: application/json

### 
GET http://localhost:8080/refs/test38420935 HTTP/1.1
content-type: application/json

### 
GET http://localhost:8080/records HTTP/1.1
content-type: application/json


### 
POST http://localhost:8080/records HTTP/1.1
content-type: application/json

{
    "id": "dskjghdskjw0448092",
    "fields": {
        "toad": "tulip",
        "totally": "blabla"
    },
    "ref_id": "test38420935"
}