@url = http://localhost:8080

### 
# @name getRef
GET {{url}}/refs HTTP/1.1
content-type: application/json

@ref_id1 = {{getRef.response.body.0.id}}
@ref_id2 = {{getRef.response.body.1.id}}


### 
POST http://localhost:8080/cols HTTP/1.1
content-type: application/json

{
    "name": "REE_NOGAAAAAA_DATE",
    "colType": "DATE",
    "ref_id": "{{ref_id1}}",
    "dateFormat": "DD MM AAAA"
}


### 
POST http://localhost:8080/cols HTTP/1.1
content-type: application/json

{
    "name": "REE_NOGA_NUMBER",
    "colType": "FK",
    "ref_id": "{{ref_id1}}",
    "pointedRefId": "blabla",
    "pointedRefColId": "lalalalala"
}

### 
POST http://localhost:8080/cols HTTP/1.1
content-type: application/json

{
    "name": "REE_ADDRESSE",
    "colType": "NONE",
    "ref_id": "{{ref_id2}}"
}

### 
GET http://localhost:8080/cols/003a5620-9f95-43d6-8af7-c9eb56e4d8d6 HTTP/1.1
content-type: application/json

###
GET http://localhost:8080/refs/b8cfc092-4d08-4a0d-9cfc-4471b8f5c865

### 
GET http://localhost:8080/cols?ref_id={{ref_id2}} HTTP/1.1
content-type: application/json
