@url = http://localhost:8080

###
POST {{url}}/entries HTTP/1.1
content-type: application/json

{
}

### 
# @name getRefForView
GET {{url}}/refs HTTP/1.1
content-type: application/json

@refid1 = {{getRefForView.response.body.0.id}}
@ref1_colid1 = {{getRefForView.response.body.0.columns.0.id}}
@ref2_colid1 = {{getRefForView.response.body.1.columns.0.id}}

###
POST {{url}}/refs HTTP/1.1
content-type: application/json

{
    "name": "Max Havelar Tomatos Referential",
    "description": "aksas"
}


###
POST {{url}}/cols HTTP/1.1
content-type: application/json

{
    "colType": "NONE",
    "refid": " "
}

###aaaaPOST {{url}}/entries HTTP/1.1
Content-Type: application/json

{
    "refid": "{{refid1}}",
    "fields": {
        "35b5aac2-3f8e-4796-ad99-e7f909b2a931": "asljsdkg"
    }
}

###
POST {{url}}/views HTTP/1.1
Content-Type: application/json

{
    "refid": "{{refid1}}",
    "dispColIds": ["{{ref1_colid1}}"]
}

###
GET {{url}}/views