### 
# @name getFirstRef
GET http://localhost:8080/refs HTTP/1.1
content-type: application/json

@firstRefId = {{getFirstRef.response.body.0.id}}

###
GET http://localhost:8080/entries HTTP/1.1
content-type: application/json

###
GET http://localhost:8080/entries?ref_id={{firstRefId}} HTTP/1.1
content-type: application/json


###
GET http://localhost:8080/refs/{{firstRefId}} HTTP/1.1
content-type: application/json

###
GET http://localhost:8080/refs/randomjunk HTTP/1.1
content-type: application/json

### 
# @name createFirstRef 
POST http://localhost:8080/refs HTTP/1.1
content-type: application/json

{
    "description": "Papayas and Cie Data",
    "name": "Papaya Ref AAA"
}

@createdFirstRefId = {{createFirstRef.response.body.id}}

###
PUT http://localhost:8080/refs/{{createdFirstRefId}}
content-type: application/json

{
  "name": "New Papaya Ref",
  "description": "Papayas SA"
}

### 
GET http://localhost:8080/refs/{{createdFirstRefId}} HTTP/1.1
content-type: application/json
