@url = http://localhost:8080

######################################################
#                  TEST REFERENTIALS                 #
######################################################

###
# @name getRef
POST {{url}}/refs

{
  "code": "X25",
  "name": "REF_BANANAS"
}

@refid = {{getRef.response.body.id}}

###
PUT {{url}}/refs/{{refid}}

{
  "code": null,
  "name": " ",
  "description": "this is a test"
}

###
GET {{url}}/refs


######################################################
#                    TEST COLFIGS                    #
######################################################


###
# @name getColfig
POST {{url}}/cols

{
  "refid": "{{refid}}",
  "name": "COLUMN_1",
  "required": false,
  "filecolname": "Column 1",
  "coltype": "BK"
}

@colfigId = {{getColfig.response.body.id}}

###
PUT {{url}}/cols/{{colfigId}}

{
  "id": "{{colfigId}}",
  "refid": "{{refid}}",
  "name": "COLUMN_1_BK",
  "required": false,
  "filecolname": " ",
  "coltype": "BK"
}

###
POST {{url}}/cols

{
  "refid": "{{refid}}",
  "name": "COLUMN_2",
  "required": false,
  "filecolname": "Column 2",
  "coltype": "BK"
}

###
GET {{url}}/cols

###
POST {{url}}/entries
