@url = http://localhost:8080

### 
# @name getRefForView
GET {{url}}/refs HTTP/1.1
content-type: application/json

@ref_id1 = {{getRefForView.response.body.0.id}}

### 
POST {{url}}/cols HTTP/1.1
content-type: application/json

{
    "name": "Nom",
    "colType": "NONE",
    "ref_id": "{{ref_id1}}"
}

### 
POST {{url}}/cols HTTP/1.1
content-type: application/json

{
    "name": "Numéro",
    "colType": "NONE",
    "ref_id": "{{ref_id1}}"
}

### 
POST {{url}}/cols HTTP/1.1
content-type: application/json

{
    "name": "Description",
    "colType": "NONE",
    "ref_id": "{{ref_id1}}"
}

###
# @name getRefColumns
GET {{url}}/cols?ref_id={{ref_id1}}


@col_id1 = {{getRefColumns.response.body.0.id}}
@col_id2 = {{getRefColumns.response.body.1.id}}
@col_id3 = {{getRefColumns.response.body.2.id}}

###
POST {{url}}/views
content-type: application/json

{
    "name": "AWESOME_VIEW",
    "ref_id": "{{ref_id1}}",
    "dispColIds": ["{{col_id1}}", "{{col_id3}}"],
    "searchColIds": ["{{col_id2}}"]
}

###
GET {{url}}/views